language: java

matrix:
  include:
    - jdk: oraclejdk8
    - sudo: required
      dist: trusty
      group: edge
      jdk: oraclejdk9
      addons:
        apt:
          packages:
            - oracle-java9-installer
            - oracle-java9-set-default
  allow_failures:
    - jdk: oraclejdk9

before_install:
  - export MAVEN_SKIP_RC=true